// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUhRTkuOZnhD5ObWrKrbRk5L2GIH0MjE',
    appId: '1:320062069119:web:299f929ce78274c26e624a',
    messagingSenderId: '320062069119',
    projectId: 'chatapptest-42824',
    authDomain: 'chatapptest-42824.firebaseapp.com',
    storageBucket: 'chatapptest-42824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0HpA6TvnYQRnb_CI137eRW3eJZnbvlA',
    appId: '1:320062069119:android:4d02558c3be0e9316e624a',
    messagingSenderId: '320062069119',
    projectId: 'chatapptest-42824',
    storageBucket: 'chatapptest-42824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwWieOIQQWH5FEZtDOwsespB5KcxNq10',
    appId: '1:320062069119:ios:fc5268b01e9b4c9e6e624a',
    messagingSenderId: '320062069119',
    projectId: 'chatapptest-42824',
    storageBucket: 'chatapptest-42824.firebasestorage.app',
    iosBundleId: 'com.example.gignegoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUwWieOIQQWH5FEZtDOwsespB5KcxNq10',
    appId: '1:320062069119:ios:fc5268b01e9b4c9e6e624a',
    messagingSenderId: '320062069119',
    projectId: 'chatapptest-42824',
    storageBucket: 'chatapptest-42824.firebasestorage.app',
    iosBundleId: 'com.example.gignegoNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTUhRTkuOZnhD5ObWrKrbRk5L2GIH0MjE',
    appId: '1:320062069119:web:a9e37ae434abfe5d6e624a',
    messagingSenderId: '320062069119',
    projectId: 'chatapptest-42824',
    authDomain: 'chatapptest-42824.firebaseapp.com',
    storageBucket: 'chatapptest-42824.firebasestorage.app',
  );
}
